//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSVApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int SV_ID { get; set; }
        public string SV_Name { get; set; }
        public string SV_Phone { get; set; }
        public string SV_Email { get; set; }
    }
}
